### ISSUE TITLE
Search ordering

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/new-salem-pelican#11]
From Ben:

> Retrieval by dates(for example all of April) for for , say, and retrieval by several months  March, April, and May retrieving all those documents in chronological order - is crucial to advancing the site's scholarly usefulness.  
> 
> Just to reiterate, retrieval by name, for example, Mary Walcott (in all versions of her name), should be returned in chronological order.

**Comment by shane-et-al** [comment]
There's two issues here: the ability to search for specific documents by date and the reordering of the person-tags results.

Search currently operates on a per-document level even though the pages are divided a per-case. The idea was that the search result link could pass in specific id for each document within a case-page.

For the first part, we currently grab only the first date for a case in the SWP.xml and assign that as the date for the entire case-page. To implement this change, we need to grab the canonical date for each document and append them to the search index. Doing this will also allow us to list a range of dates for the case-page-level metadata, so we can indicate that the entire case didn't happen just on the day that the first document happened. This is fairly straightforward, but requires touching the code on different parts of almost every level of the new-salem code: translator, markdown format, search indexer, and search page. 

The second part is potentially a little to very tricky. For just the search ordering, we just need to port some of the TOC ordering logic to the articles list. The only new logic will be to switch the ordering system based on view context, which may require some hacky flag passing. But since the people-tags, like all the non-search parts of the site, operate on a case-page level, we don't have a good way to differentiate them on an document level. So if Ben wants the people-search to return actual documents, then a serious rework of that whole system may be necessary.

**Comment by shane-et-al** [comment]
Because I forgot to update this... search corpus pulls the canonical date for each document now and does not attach any date to those without them. So this the first part is mostly done, save for the date range search and the chronological sorting. ("This is fairly straightforward" oh god, never again)

The second part remains intransigent and we should push back on it as it is entirely new functionality. Sorting by the case date is easy enough, but it's too much work to get person-search to function on a document level.

**Comment by shane-et-al** [comment]
As of d964d507420624931b0c842108cc3331ae09000e , the tag pages are now sorted by date, but still at the case level.

**Comment by shane-et-al** [comment]
Per conversation with Ben today, implication that person-searching on a case level is maybe not optimal, but acceptable since person-searching is new functionality. Issue mitigated by #19.

Still need to fix tag page ordering, since d964d507420624931b0c842108cc3331ae09000e is reversed order (should be earliest-first).

**Comment by shane-et-al** [comment]
Tag page sorting is now correctly ordered earliest-fixed per 2ed940d68c140c9804c0bcabd5b02a9981410a03

Names in tag list page are now also sorted, by tag-id.

**Comment by shane-et-al** [comment]
Since we hacked the document display, we're not going to change the person tagging. #wontfix
