### ISSUE TITLE
Selected Literary Works Section: Oliver Wendell Holmes

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#33]
Link to works of Oliver Wendell Holmes from http://newsalem.scholarslab.org/lit.html is non-functional.

**Comment by rondauva** [comment]
The library collection of digital texts by Wendell Holmes consists of 7 items. I'll email Ben and ask which of these Ben wants us to link from the catalog.

**Comment by shane-et-al** [comment]
Fixed the link to point at the XTF host poem that Ben indicated (b982ea1407dc2b361e02c156dd312b613411366e)

We need to migrate off of that, probably to just a simple static page once some of the other such things get styled. Going to swap the tag from content upgrade to long-term.

**Comment by shane-et-al** [comment]
This is the poem, in case the XTF host blows up without warning:


THE BROOMSTICK TRAIN; OR, THE RETURN OF THE WITCHES
If there are any anachronisms or other inaccuracies in this story, the reader will please to remember that the narrator's memory is liable to be at fault, and if the event recorded interests him, will not worry over any little slips or stumbles.
The terrible witchcraft drama of 1692 has been seriously treated, as it well deserves to be. The story has been told in two large volumes by the Rev. Charles Wentworth Upham, and in a small and more succinct volume, based upon his work, by his daughter-in-law, Caroline E. Upham.

The delusion, commonly spoken of as if it belonged to Salem, was more widely diffused through the towns of Essex County. Looking upon it as a pitiful and long dead and buried superstition, I trust my poem will no more offend the good people of Essex County than Tam O'Shanter worries the honest folk of Ayrshire.

The localities referred to are those with which I am familiar in my drives about Essex County.

Look out! Look out, boys! Clear the track!
The witches are here! They've all come back!
They hanged them high,—No use! No use!
What cares a witch for a hangman's noose?
They buried them deep, but they would n't lie still,
For cats and witches are hard to kill;
They swore they should n't and would n't die,—
Books said they did, but they lie! they lie!
A couple of hundred years, or so,
They had knocked about in the world below,
When an Essex Deacon dropped in to call,
And a homesick feeling seized them all;
For he came from a place they knew full well,
And many a tale he had to tell.
They longed to visit the haunts of men,
To see the old dwellings they knew again,
And ride on their broomsticks all around
Their wide domain of unhallowed ground.
In Essex county there 's many a roof
Well known to him of the cloven hoof;
The small square windows are full in view
Which the midnight hags went sailing through,
On their well-trained broomsticks mounted high,
Seen like shadows against the sky;
Crossing the track of owls and bats,
Hugging before them their coal-black cats.
Well did they know, those gray old wives,
The sights we see in our daily drives:
Shimmer of lake and shine of sea,
Browne's bare hill with its lonely tree,
(It was n't then as we see it now,
With one scant scalp-lock to shade its brow;)
Dusky nooks in the Essex woods,
Dark, dim, Dante-like solitudes,
Where the tree-toad watches the sinuous snake
Glide through his forests of fern and brake;
Ipswich River; its old stone bridge;
Far off Andover's Indian Ridge,
And many a scene where history tells
Some shadow of bygone terror dwells,—
Of “Norman's Woe” with its tale of dread,
Of the Screeching Woman of Marblehead,
(The fearful story that turns men pale:
Don't bid me tell it,—my speech would fail.)
Who would not, will not, if he can,
Bathe in the breezes of fair Cape Ann,—
Rest in the bowers her bays enfold,
Loved by the sachems and squaws of old?
Home where the white magnolias bloom,
Sweet with the bayberry's chaste perfume,
Hugged by the woods and kissed by the sea!
Where is the Eden like to thee?
For that “couple of hundred years, or so,”
There had been no peace in the world below;
The witches still grumbling, “It is n't fair;
Come, give us a taste of the upper air!
We 've had enough of your sulphur springs,
And the evil odor that round them clings;
We long for a drink that is cool and nice,—
Great buckets of water with Wenham ice;
We 've served you well up-stairs, you know;
You 're a good old—fellow—come, let us go!”
I don't feel sure of his being good,
But he happened to be in a pleasant mood,—
As fiends with their skins full sometimes are,—
303
(He 'd been drinking with “roughs” at a Boston bar.)
So what does he do but up and shout
To a graybeard turnkey, “Let 'em out!”
To mind his orders was all he knew;
The gates swung open, and out they flew.
“Where are our broomsticks?” the beldams cried.
“Here are your broomsticks,” an imp replied.
“They 've been in—the place you know—so long
They smell of brimstone uncommon strong;
But they 've gained by being left alone,—
Just look, and you'll see how tall they 've grown.”
“And where is my cat?” a vixen squalled.
“Yes, where are our cats?” the witches bawled,
And began to call them all by name:
As fast as they called the cats, they came:
There was bob-tailed Tommy and long-tailed Tim,
And wall-eyed Jacky and green-eyed Jim,
And splay-foot Benny and slim-legged Beau,
And Skinny and Squally, and Jerry and Joe,
And many another that came at call,—
It would take too long to count them all.
All black,—one could hardly tell which was which,
But every cat knew his own old witch;
And she knew hers as hers knew her,—
Ah, did n't they curl their tails and purr!
No sooner the withered hags were free
Than out they swarmed for a midnight spree;
I could n't tell all they did in rhymes,
But the Essex people had dreadful times.
The Swampscott fishermen still relate
How a strange sea-monster stole their bait;
How their nets were tangled in loops and knots,
And they found dead crabs in their lobster-pots,
Poor Danvers grieved for her blasted crops,
And Wilmington mourned over mildewed hops.
A blight played havoc with Beverly beans.—
It was all the work of those hateful queans!
A dreadful panic began at “Pride's,”
Where the witches stopped in their midnight rides,
And there rose strange rumors and vague alarms
'Mid the peaceful dwellers at Beverly Farms.
Now when the Boss of the Beldams found
That without his leave they were ramping round,
He called,—they could hear him twenty miles,
From Chelsea beach to the Misery Isles;
The deafest old granny knew his tone
Without the trick of the telephone.
“Come here, you witches! Come here!” says he,—
“At your games of old, without asking me!
I'll give you a little job to do
That will keep you stirring, you godless crew!”
They came, of course, at their master's call,
The witches, the broomsticks, the cats, and all;
He led the hags to a railway train
The horses were trying to drag in vain.
“Now, then,” says he, “you 've had your fun,
And here are the cars you 've got to run.
The driver may just unhitch his team,
We don't want horses, we don't want steam;
You may keep your old black cats to hug,
But the loaded train you 've got to lug.”
Since then on many a car you'll see
A broomstick plain as plain can be;
On every stick there 's a witch astride,—
The string you see to her leg is tied.
She will do a mischief if she can,
But the string is held by a careful man,
And whenever the evil-minded witch
Would cut some caper, he gives a twitch.
As for the hag, you can't see her,
But hark! you can hear her black cat's purr,
And now and then, as a car goes by,
You may catch a gleam from her wicked eye.
Often you 've looked on a rushing train,
But just what moved it was not so plain.
It could n't be those wires above,
For they could neither pull nor shove;

**Comment by shane-et-al** [comment]
Since there's other XTF content on Salem there that's larger than just this and we've decided that it's out of our hands to unilaterally ensure availability of that corpus, I'm going to kick this one down the road.
